### ISSUE TITLE
resnet url is unavailable and in BatchPreprocessor the mean_color is from ImageNet?

### ISSUE THREAD

**Issue by xiexie123** [dgurkaynak/marvel-finetuning#1]
hi,
 the url in resnet download_weights.sh is unavailable....
could you offer another link for us?
or just upload the npy file?

BTW, the mean_color=[132.2766, 139.6506, 146.9702] in BatchPreprocessor is from ImageNet or CIFAR?

**Comment by dgurkaynak** [comment]
Hey @xiexie123, sorry for late reply. Yeah dropbox seems to prevent downloading files from scripts. I will try to fix it. Meanwhile you can manually download them and move to `resnet` folder. 

Download links:
https://www.dropbox.com/s/txb16f1khleyvdh/ResNet-L50.npy
https://www.dropbox.com/s/8w10cs6v4rd9616/ResNet-L101.npy
https://www.dropbox.com/s/n5inup5a7fi8lom/ResNet-L152.npy

(132.2766, 139.6506, 146.9702) is the mean color of ImageNet.
