### ISSUE TITLE
A problem about fine-tuning for resnet

### ISSUE THREAD

**Issue by pyni** [dgurkaynak/marvel-finetuning#12]
Hi, I wonder why there are so many steps  to finetune resnet?

**Comment by dgurkaynak** [comment]
What do you mean so many steps?

**Comment by pyni** [comment]
In tensorflow-cnn-finetune/resnet/examples.sh:
These steps:

python finetune.py \
	--learning_rate "0.00001" \
	--train_layers "fc"

python finetune.py \
	--learning_rate "0.00001" \
	--train_layers "fc,scale5/block3"

python finetune.py \
	--learning_rate "0.00001" \
	--train_layers "fc,scale5/block3,scale5/block2"

python finetune.py \
	--learning_rate "0.00001" \
	--train_layers "fc,scale5/block3,scale5/block2,scale5/block1"

python finetune.py \
	--learning_rate "0.00001" \
	--multi_scale "225,256" \
	--train_layers "fc,scale5"

python finetune.py \
	--learning_rate "0.00001" \
	--multi_scale "225,256" \
	--train_layers "fc,scale5,scale4/block6"

python finetune.py \
	--learning_rate "0.00001" \
	--multi_scale "225,256" \
	--train_layers "fc,scale5,scale4/block6,scale4/block5"

**Comment by dgurkaynak** [comment]
These are 7 different individual finetuning example**s**, they all finetune different layers as you can see. They are not sequential steps or something like that. You gotta call just once `python finetune.py` with your desired parameters.

**Comment by pyni** [comment]
I see. Thanks!
