### ISSUE TITLE
ImportError:cannot import name BatchPreprocessor

### ISSUE THREAD

**Issue by ShiningRuby** [dgurkaynak/marvel-finetuning#2]
I download preprocessor，but there is no function named BatchPreprocessor in the package.What makes me confused is that i've run the file two months ago,no error happened.

**Comment by dgurkaynak** [comment]
`BatchPreprocessor` class is in `utils/preprocessor.py`. You need to add `utils` folder to system paths before using.

Check https://github.com/dgurkaynak/tensorflow-cnn-finetune/blob/master/alexnet/finetune.py#L6-L7
```python
sys.path.insert(0, '../utils')
from preprocessor import BatchPreprocessor
```

How do you get this error?

**Comment by ShiningRuby** [comment]
I'm sorry to bother you,there was something wrong when importing the utils folder,and now it's OK
