### ISSUE TITLE
support for multi-GPU

### ISSUE THREAD

**Issue by DavyMorgan** [dgurkaynak/marvel-finetuning#3]
hi, I really appreciate that you have done this great job. I have implemented your code on my own machine with 4 GPUs. However, even though it occupies all the 4 GPUs, there is only 1 GPU really computing which can be showed by Volatile GPU-Util if you command nvidia-smi. It seems that your code doesn't support multi-GPU training. I'm wondering whether you have plans to support multi-GPU? Appreciate!

**Comment by dgurkaynak** [comment]
Hey @DavyMorgan, currently I have no plans to support multiple GPUs. But any PRs are very well welcome (:
