### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by IGI123** [dgurkaynak/marvel-finetuning#9]
Traceback (most recent call last):
  File "finetune.py", line 155, in <module>
    tf.app.run()
  File "/home/lshl/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "finetune.py", line 87, in main
    output_size=[224, 224], horizontal_flip=True, shuffle=True, multi_scale=multi_scale)
  File "../utils/preprocessor.py", line 29, in __init__
    self.labels.append(int(items[1]))
IndexError: list index out of range 

When I finetune the alexnet, it has a error ,i couldn't find what the matter .Can you give me some advice?

**Comment by IGI123** [comment]
。

**Comment by dgurkaynak** [comment]
Hey @IGI123, did you fix the issue?

**Comment by IGI123** [comment]
Yes，I have fixed. And you have trained the inceptionet？

**Comment by IGI123** [comment]
@dgurkaynak it's the problem of train.txt.

**Comment by dgurkaynak** [comment]
> Yes，I have fixed. And you have trained the inceptionet？

Nope, also not planning to implement it in near future due to lack of time.

**Comment by Icey-r** [comment]
The same problem.How did you fix it? Can you tell me some details about train.txt?

**Comment by dgurkaynak** [comment]
> The same problem.How did you fix it? Can you tell me some details about train.txt?

Check if file paths and class indexes in the train.txt are correct, see: https://github.com/dgurkaynak/tensorflow-cnn-finetune#custom-dataset
